export function initProjects(c){
  const {$,$$,reduced,finePointer,gsapReady,gsap,root,lenis}=c;
  const data=[
    {title:'Casa Alma',type:'Interiores',place:'Sorocaba — SP · 2026',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2200&q=88'},
    {title:'Apartamento Luz',type:'Reforma',place:'Campolim — SP · 2026',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=88'},
    {title:'Casa Entre',type:'Arquitetura',place:'Interior — SP · 2025',image:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=2200&q=88'},
    {title:'Refúgio 06',type:'Interiores',place:'Sorocaba — SP · 2025',image:'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=2200&q=88'}];
  const modal=$('.project-modal');let active=0,returnFocus=null;
  const hydrate=index=>{active=(index+data.length)%data.length;const d=data[active],img=$('.project-modal-media img');if(img){img.src=d.image;img.alt=`${d.title} — ${d.type}`}$('.modal-type').textContent=d.type;$('.modal-title').textContent=d.title;$('.modal-place').textContent=d.place;$('.modal-current').textContent=String(active+1).padStart(2,'0')};
  const open=(index,source)=>{if(!modal)return;returnFocus=source||document.activeElement;const mutate=()=>{hydrate(index);modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');root.style.overflow='hidden';lenis?.stop()};document.startViewTransition&&!reduced?document.startViewTransition(mutate):mutate();if(gsapReady&&!reduced){gsap.fromTo('.project-modal-media',{clipPath:'inset(12% 10% 12% 22%)',scale:.94},{clipPath:'inset(0% 0% 0% 0%)',scale:1,duration:.9,ease:'expo.out'});gsap.fromTo('.project-modal-copy>*',{y:30,opacity:0},{y:0,opacity:1,stagger:.07,duration:.65,ease:'power3.out',delay:.18})}setTimeout(()=>$('.project-modal-close')?.focus(),80)};
  const close=()=>{if(!modal)return;const done=()=>{modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');root.style.overflow='';lenis?.start();returnFocus?.focus?.()};gsapReady&&!reduced?gsap.to(modal,{opacity:0,duration:.28,onComplete:()=>{done();gsap.set(modal,{clearProps:'opacity'})}}):done()};
  $$('[data-open-project]').forEach(btn=>btn.addEventListener('click',()=>open(Number(btn.dataset.openProject),btn)));$('.project-modal-close')?.addEventListener('click',close);$('.modal-next')?.addEventListener('click',()=>hydrate(active+1));$('.modal-prev')?.addEventListener('click',()=>hydrate(active-1));modal?.addEventListener('click',e=>{if(e.target===modal)close()});addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('is-open'))close()});
  if(finePointer&&!reduced&&gsapReady)$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;gsap.to(el,{x:x*.13,y:y*.13,duration:.35,ease:'power3.out',overwrite:true})});el.addEventListener('pointerleave',()=>gsap.to(el,{x:0,y:0,duration:.55,ease:'elastic.out(1,.55)'}))});
}
