export function initScenes(c){
  const {$,$$,clamp,reduced,gsapReady,gsap,ScrollTrigger,mobile,cinematicScrollTo,glUniforms,getPointer}=c;
  if(reduced||!gsapReady)return;
  const chapterIndex=$('.chapter-index'),chapterName=$('.chapter-name');
  const setChapter=scene=>{if(chapterIndex)chapterIndex.textContent=scene.dataset.chapter||'00';if(chapterName)chapterName.textContent=scene.dataset.name||'TENKA';if(glUniforms){const light=['01','03','06','07'].includes(scene.dataset.chapter);gsap.to(glUniforms.uIntensity,{value:light?.22:.52,duration:.8})}};
  $$('.scene[data-chapter]').forEach(scene=>ScrollTrigger.create({trigger:scene,start:'top 52%',end:'bottom 48%',onEnter:()=>setChapter(scene),onEnterBack:()=>setChapter(scene)}));

  gsap.timeline({defaults:{ease:'power4.out'},delay:.45}).from('.brand',{y:-18,opacity:0,duration:.7}).from('.menu-toggle',{y:-18,opacity:0,duration:.7},'-=.62').from('.hero-eyebrow',{y:18,opacity:0,duration:.75},'-=.52').from('.hero-title .hero-line>span',{yPercent:116,duration:1.2,stagger:.12},'-=.45').from('.hero-caption',{y:24,opacity:0,duration:.85},'-=.75').from('.hero-aperture',{scale:.65,opacity:0,duration:1.1,ease:'expo.out'},'-=1').from('.hero-timecode,.scroll-hint',{opacity:0,duration:.6,stagger:.1},'-=.55');

  const mm=gsap.matchMedia();
  mm.add({desktop:'(min-width: 901px)',mobile:'(max-width: 900px)'},ctx=>{
    const isMobile=ctx.conditions.mobile;
    gsap.timeline({scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom bottom',scrub:isMobile?.55:1.15}}).to('.hero-backdrop',{scale:isMobile?1.12:1.2,xPercent:isMobile?-2:-4,ease:'none',duration:1},0).to('.hero-aperture',{width:'106vw',height:'106vh',left:'50%',top:'50%',borderColor:'rgba(255,255,255,0)',ease:'power2.inOut',duration:.66},.16).to('.hero-copy',{scale:isMobile?1.08:1.17,xPercent:isMobile?-5:-12,opacity:0,ease:'power2.in',duration:.34},.3).to('.hero-caption,.hero-timecode,.scroll-hint',{opacity:0,duration:.2},.26).to('.hero-backdrop',{filter:'blur(5px) brightness(.7)',duration:.3},.66).to('.hero-aperture',{filter:'brightness(1.25)',duration:.3},.68);
    const heroWorld=$('.hero-world');if(heroWorld&&!isMobile)gsap.ticker.add(()=>{const p=getPointer();heroWorld.style.transform=`rotateX(${p.y*-.55}deg) rotateY(${p.x*.8}deg)`});

    const words=$$('.manifesto-title span');gsap.set(words,{opacity:.12,yPercent:55});gsap.timeline({scrollTrigger:{trigger:'.manifesto',start:'top top',end:'bottom bottom',scrub:isMobile?.5:.9}}).to(words,{opacity:1,yPercent:0,stagger:.025,ease:'power3.out',duration:.42},0).fromTo('.manifesto-window',{clipPath:'inset(100% 0 0 0)'},{clipPath:'inset(0% 0 0 0)',ease:'power3.inOut',duration:.35},.22).to('.manifesto-window',{yPercent:38,scale:1.15,ease:'none',duration:.48},.37).to(words.filter((_,i)=>i%3===0),{xPercent:isMobile?-5:-12,ease:'none',duration:.42},.42).to(words.filter((_,i)=>i%3===1),{xPercent:isMobile?4:9,ease:'none',duration:.42},.42).to('.manifesto-side',{yPercent:-18,ease:'none',duration:.3},.55).to('.manifesto-title',{opacity:.08,scale:1.08,ease:'power2.in',duration:.18},.82).to('.manifesto-window',{width:isMobile?'100vw':'106vw',height:'106vh',right:isMobile?'-7vw':'-9vw',top:'-3vh',duration:.22,ease:'power3.inOut'},.79);

    const shots=$$('.story-visual'),copies=$$('.story-copy'),storyNav=$$('.story-nav');gsap.set(shots,{opacity:0});gsap.set(shots[0],{opacity:1});gsap.set(copies,{opacity:0,y:55});gsap.set(copies[0],{opacity:1,y:0});gsap.timeline({scrollTrigger:{trigger:'.story',start:'top top',end:'bottom bottom',scrub:isMobile?.55:.95,onUpdate:self=>{const i=Math.min(2,Math.floor(self.progress*3));storyNav.forEach((b,n)=>b.classList.toggle('active',n===i))}}}).to('.story-progress i',{scaleX:1,ease:'none',duration:3},0).to(shots[0],{scale:1,duration:.85,ease:'none'},0).to(copies[0],{y:-45,opacity:0,duration:.18},.78).to(shots[0],{opacity:0,scale:.96,duration:.18},.79).fromTo(shots[1],{opacity:0,clipPath:'inset(18% 20% 18% 20%)',scale:1.12},{opacity:1,clipPath:'inset(0% 0% 0% 0%)',scale:1.03,duration:.28,ease:'power2.inOut'},.82).to('.technical-layer',{opacity:.82,duration:.24},.9).to(copies[1],{opacity:1,y:0,duration:.22,ease:'power3.out'},.94).to('.technical-layer .axis.ax',{scaleX:.4,transformOrigin:'center',duration:.45,ease:'none'},1.04).to('.technical-layer .axis.ay',{scaleY:.55,transformOrigin:'center',duration:.45,ease:'none'},1.04).to(copies[1],{y:-45,opacity:0,duration:.18},1.73).to('.technical-layer',{opacity:0,duration:.18},1.77).to(shots[1],{opacity:0,scale:.98,duration:.2},1.78).fromTo(shots[2],{opacity:0,clipPath:'circle(12% at 72% 46%)',scale:1.12},{opacity:1,clipPath:'circle(85% at 72% 46%)',scale:1.02,duration:.34,ease:'power3.inOut'},1.8).to('.story-light',{opacity:1,duration:.3},1.9).to(copies[2],{opacity:1,y:0,duration:.22,ease:'power3.out'},1.95).to(shots[2],{scale:1,duration:.75,ease:'none'},2.15);

    gsap.timeline({scrollTrigger:{trigger:'.transformation',start:'top top',end:'bottom bottom',scrub:isMobile?.5:.9}}).from('.transformation-head h2',{yPercent:28,opacity:0,duration:.22,ease:'power3.out'},0).to('.transformation-stage',{scale:isMobile?1:1.03,duration:.4,ease:'none'},.12).to('.drawing-overlay',{opacity:.82,duration:.24},.26).to('.state-before img',{filter:'saturate(.25) contrast(1.12)',duration:.25},.27).to('.state-after',{clipPath:'inset(0 48% 0 0)',duration:.25,ease:'power2.inOut'},.48).to('.drawing-overlay',{opacity:.28,duration:.2},.55).to('.state-after',{clipPath:'inset(0 0% 0 0)',duration:.32,ease:'power3.inOut'},.66).to('.state-after img',{scale:1.05,duration:.34,ease:'none'},.66).to('.drawing-overlay',{opacity:0,duration:.18},.75).to('.transformation-note',{yPercent:-15,duration:.25,ease:'none'},.72);

    const projects=$$('.project-shot'),reelCurrent=$('.project-reel-index span:first-child'),reelBar=$('.project-reel-index i');ScrollTrigger.create({trigger:'.projects',start:'top top',end:'bottom bottom',scrub:true,onUpdate:self=>{const q=clamp((self.progress-.13)/.87),scaled=q*projects.length,index=Math.min(projects.length-1,Math.floor(scaled));projects.forEach((project,i)=>{const delta=i-scaled+.18,d=Math.abs(delta),opacity=clamp(1-d*1.6),y=delta*(isMobile?16:22),scale=1-Math.min(d,1)*.07;project.style.opacity=opacity;project.style.transform=`translate3d(0,${y}vh,0) scale(${scale})`;project.style.pointerEvents=opacity>.65?'auto':'none';project.classList.toggle('active',i===index);const img=$('figure img',project);if(img)img.style.transform=`scale(${1.1+Math.min(d,1)*.04}) translate3d(0,${delta*-2.5}%,0)`});if(reelCurrent)reelCurrent.textContent=String(index+1).padStart(2,'0');if(reelBar)reelBar.style.background=`linear-gradient(to bottom,#fff ${q*100}%,rgba(255,255,255,.24) ${q*100}%)`}});gsap.timeline({scrollTrigger:{trigger:'.projects',start:'top top',end:'18% top',scrub:.5}}).to('.projects-intro',{opacity:0,y:-55,scale:.96,ease:'power2.in'});

    const serviceLines=$$('.service-line'),serviceBgs=$$('.services-backdrops figure');ScrollTrigger.create({trigger:'.services',start:'top top',end:'bottom bottom',scrub:true,onUpdate:self=>{const index=Math.min(2,Math.floor(self.progress*3));serviceLines.forEach((el,i)=>el.classList.toggle('active',i===index));serviceBgs.forEach((el,i)=>{el.classList.toggle('active',i===index);const local=clamp(self.progress*3-i);el.style.transform=`scale(${1.08-local*.05}) translate3d(${(i-self.progress*3)*1.5}%,0,0)`})}});gsap.from('.services-heading',{y:50,opacity:0,scrollTrigger:{trigger:'.services',start:'top 70%',toggleActions:'play none none reverse'},duration:.9,ease:'power3.out'});

    gsap.timeline({scrollTrigger:{trigger:'.philosophy',start:'top top',end:'bottom bottom',scrub:isMobile?.4:.8}}).from('.philosophy-sticky h2',{yPercent:22,opacity:.05,scale:.94,duration:.32,ease:'power3.out'}).from('.philosophy-sticky>p',{y:45,opacity:0,duration:.22},.18).from('.philosophy-words span',{y:18,opacity:0,stagger:.04,duration:.25},.2).to('.philosophy-line',{scaleX:.25,transformOrigin:'left',duration:.4,ease:'none'},.45).to('.philosophy-sticky h2',{xPercent:isMobile?-4:-9,duration:.42,ease:'none'},.47).to('.philosophy-words span',{xPercent:i=>(i-2)*(isMobile?8:18),duration:.42,ease:'none'},.47);

    const processSteps=$$('.process-step');ScrollTrigger.create({trigger:'.process',start:'top top',end:'bottom bottom',scrub:true,onUpdate:self=>{const scaled=self.progress*processSteps.length,index=Math.min(processSteps.length-1,Math.floor(scaled));processSteps.forEach((el,i)=>{const d=Math.abs(i-scaled+.15);el.style.opacity=clamp(1-d*1.4);el.style.transform=`translate3d(0,${(i-scaled)*35}px,0)`;el.classList.toggle('active',i===index)});const rail=$('.process-rail i');if(rail)rail.style.transform=`scaleY(${self.progress})`}});gsap.to('.process-blueprint span:nth-child(1)',{xPercent:60,scrollTrigger:{trigger:'.process',start:'top top',end:'bottom bottom',scrub:true}});gsap.to('.process-blueprint span:nth-child(2)',{yPercent:-80,scrollTrigger:{trigger:'.process',start:'top top',end:'bottom bottom',scrub:true}});

    gsap.timeline({scrollTrigger:{trigger:'.outro',start:'top top',end:'bottom bottom',scrub:isMobile?.5:.9}}).to('.outro-bg img',{scale:1,ease:'none',duration:.62},0).from('.outro-copy .eyebrow',{opacity:0,y:20,duration:.18},.1).from('.outro-copy h2',{opacity:0,yPercent:18,duration:.28,ease:'power3.out'},.14).from('.outro-actions',{opacity:0,y:18,duration:.2},.25).to('.outro-copy',{scale:.94,opacity:.22,duration:.18},.75).to('.outro-shutter i:first-child',{xPercent:78,duration:.22,ease:'power3.inOut'},.78).to('.outro-shutter i:last-child',{xPercent:-78,duration:.22,ease:'power3.inOut'},.78).fromTo('.credits',{opacity:0},{opacity:1,duration:.15},.88);
  });

  $$('[data-story-jump]').forEach(button=>button.addEventListener('click',()=>{const section=$('.story'),index=Number(button.dataset.storyJump||0);if(!section)return;const travel=Math.max(0,section.offsetHeight-innerHeight);cinematicScrollTo(section.offsetTop+travel*([.12,.49,.82][index]||.12),{duration:1.35})}));
}
